Update index.d.ts
fastify/fastify-static pull request #176
Opened 2021-02-20 18:42 UTC by guillenotfound

This accepts a boolean as per the docs, that way it won't load any HTML files.

https://www.npmjs.com/package/send#index

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

2021-02-20 21:06 UTC, mcollina commented
Could you please add a test for the type: test/types/index.ts?

2021-02-21 04:19 UTC, climba03003 requested changes

2021-02-21 04:19 UTC, climba03003 commented on index.d.ts
> +  index?: string[] | boolean;
```suggestion
  index?: string[] | false;
```

2021-02-21 04:19 UTC, climba03003 commented on index.d.ts
> +  index?: string[] | boolean;
```suggestion
  index?: string[] | false;
```

2021-02-21 04:19 UTC, climba03003 commented on index.d.ts
> +  index?: string[] | boolean;
It should be `false` only. 
https://github.com/pillarjs/send/blob/de073ed3237ade9ff71c61673a34474b30e5d45b/index.js#L1056

2021-02-21 04:19 UTC, climba03003 commented on index.d.ts
> +  index?: string[] | boolean;
Some as above

2021-02-22 07:35 UTC, guillenotfound commented on index.d.ts
> +  index?: string[] | boolean;
Done 👍

2021-02-22 07:35 UTC, guillenotfound commented
> Could you please add a test for the type: test/types/index.ts?

Sure, done ;)

2021-02-22 08:09 UTC, mcollina approved these changes
lgtm

2021-02-22 10:25 UTC, climba03003 approved these changes

2021-02-22 11:49 UTC, merged