Add options overload parameter to sendFile function (#238)
fastify/fastify-static pull request #239
Opened 2021-10-02 21:29 UTC by mav-rik

#### Checklist

- [X] run `npm run test` and `npm run benchmark`
- [X] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [X] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

2021-10-02 21:41 UTC, mcollina requested changes
Thanks! Could you update the README as well?

2021-10-03 07:37 UTC, mav-rik commented
@mcollina done

2021-10-03 07:53 UTC, mcollina approved these changes
lgtm

2021-10-03 08:24 UTC, Eomm reviewed
Just a hint

2021-10-03 08:24 UTC, Eomm commented on index.js
> +    fastify.decorateReply('sendFile', function (filePath, rootPath, options = {}) {
The default value is not necessary

```suggestion
    fastify.decorateReply('sendFile', function (filePath, rootPath, options) {
```

2021-10-04 07:43 UTC, mcollina approved these changes
lgtym

2021-10-05 16:40 UTC, mav-rik commented
@mcollina is it ready to be merged? Any more approves needed?

2021-10-05 17:04 UTC, mcollina commented
I just needed to ship a security release for this module. Landing this now.

2021-10-05 17:04 UTC, merged