fix: update glob to version 8 and fix broken tests
fastify/fastify-static pull request #297
Opened 2022-05-10 03:16 UTC by guilhermelimak

In this release glob stopped accepting backward slashes on it's patterns, since `path.join` wil lreturn backward slashes on windows it they have to be replaced by a forward slash which is the posix separator.

I'm not entirely sure about all the implications of this change, specially regarding performance but all the tests seem to be passing and everything should work normally AFAIK since windows accept both backward and forward slashes as path separator.

Closes #281 since glob is already being updated here.

#### Checklist

- [X] run `npm run test` and `npm run benchmark`
- [X] tests and/or benchmarks are included
- [X] documentation is changed or added
- [X] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

2022-05-10 04:21 UTC, climba03003 requested changes

2022-05-10 04:21 UTC, climba03003 commented on index.js
> +        const files = await globPromise(path.join(rootPath, globPattern).replaceAll(path.win32.sep, path.posix.sep), { nodir: true })
`.replaceAll` is not supported by `node@14`

2022-05-11 15:04 UTC, mcollina approved these changes
lgtm

2022-05-11 15:09 UTC, climba03003 approved these changes
LGTM.

2022-05-11 15:35 UTC, merged

2022-05-14 11:00 UTC, ZiiMakc commented
@mcollina can we please release a new version with this fix?

2022-05-15 12:54 UTC, mcollina commented
v6.1.0 released.