fix: allow fallback to fastify@2.22 route config
fastify/fastify-static pull request #410
Opened 2023-09-16 22:48 UTC by climba03003

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

2023-09-16 22:55 UTC, gurgunday commented on index.js
> +    const routeConfig = (req.routeOptions && req.routeConfig.config) || req.routeConfig
```suggestion
    const routeConfig = req.routeOptions?.config || req.routeConfig
```

2023-09-16 23:09 UTC, Uzlopak approved these changes
LGTM, decide if you want to apply the suggestion of @gurgunday

2023-09-16 23:10 UTC, gurgunday requested changes
I think it should be `req.routeOptions.config` instead of `req.routeConfig.config`

2023-09-16 23:51 UTC, Uzlopak commented
Very good catch!

2023-09-17 00:03 UTC, Uzlopak commented
Ok, tested it locally thoroughly, by using fastify 4.20.0 and it works. updated to latest, works and does not emit warnings. modified that line to use a different key with latest fastify, emitted warnings.

2023-09-17 00:03 UTC, Uzlopak commented
@gurgunday 
PTAL

2023-09-17 07:34 UTC, gurgunday approved these changes

2023-09-17 07:39 UTC, mcollina approved these changes
lgtm

2023-09-17 08:25 UTC, Eomm approved these changes

2023-09-17 08:25 UTC, merged